@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< Updated upstream
REM Generated by Vivado on Mon Dec 22 11:27:36 +0100 2025
=======
REM Generated by Vivado on Fri Jan 09 22:31:58 +0100 2026
>>>>>>> Stashed changes
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim TOP_TB_behav -key {Behavioral:sim_1:Functional:TOP_TB} -tclbatch TOP_TB.tcl -view C:/Users/Usuario/Downloads/2025_2026/sed/trabajo_vhdl/github/Proyecto-Nexys/registro colores/project_1/TOP_TB_behav.wcfg -log simulate.log"
call xsim  TOP_TB_behav -key {Behavioral:sim_1:Functional:TOP_TB} -tclbatch TOP_TB.tcl -view C:/Users/Usuario/Downloads/2025_2026/sed/trabajo_vhdl/github/Proyecto-Nexys/registro colores/project_1/TOP_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
